os: linux
language: shell

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
- docker

env:
  global:
  - IMAGE=gcr.io/dd-decaf-cfbf6/iam
  - BRANCH=${TRAVIS_BRANCH}
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_TIMESTAMP=$(date --utc --iso-8601=seconds)
  - BUILD_DATE=$(date --utc --iso-8601=date)
  - BUILD_TAG=${BRANCH}_${BUILD_DATE}_${SHORT_COMMIT}

before_install:
- make setup

install:
- make build
- make build-travis
- make post-build
- make start

script:
- make style
- make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
- docker-compose exec -e ENVIRONMENT=testing web pytest --cov=iam --cov-report=term --cov-report=xml
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- ./scripts/install_gcloud.sh
- ./scripts/install_kubectl.sh
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make push; fi

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "ghQhVRD9mWzOdgihij3jG0vTYifp7d6UusI5OmhGkkl9qesrpy665a5FdmDVnrIAQgjb7noJic0m32TLoq5TA0cLb9x3pISANuGY/l0ao1tBQb5few1LfsBU4eQS8vcMFeAc/BSR5QWc/x8RBt2UwbAjOfLf4/u1feLtZEOFkELJ1XQKVp6oSwLBnFHv6nwM25O1o62jmWmoY7ODzNQ1hxuGO5XE1Tb7LE7Zg47xH8ZLJ36Wjm/zgs2j4hvHM/1L1P77YVTXmHVecdBTnHgpOtCWM7fZ97N7uhQ/fU6uYQom8wyionLjINp+3DFR2a4D3YUnqQlkYOdblEMw1uXa7zMjH9WRW5RnNk0hRxcFNh6QbAByy8LbSYe53larYBox5LvqIlDI7FP2XKWfmpLK7QnUd2o4qQvPbiGWe7TsAWLuMNl5HekEOI+7XB3Xb2WRczeaxIyFwoBfBh4h+3URwMdX6yFWSgitUKSk78UvgMjI5uHm/IP0it5qU26bPw3kBpC9Dml1ht1m+YgR0zXD+IiWJtuPndRArTIB1nhN8fyINOF+Kr72E2JjZBDB14cLMdtvZPkej2uLZe+P0LoNHJTCa5EEecdUOWQPaClDXhbQv3WtQS8xgSO1Ea/jay8gU3aME0wfeHnJJs/lO6PJDj5pmt/TbEYN7N4WKMu0l6c="
    on_success: change
    on_failure: change
    on_pull_requests: false
