sudo: required
language: python
python:
  - "3.6"

git:
  depth: 3

services:
  - docker
  - postgresql

addons:
  postgresql: "9.6"  # note: travis does not yet support 10.x

install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile --system --deploy
  - psql -U postgres -c "create database iam_test;"
  - ssh-keygen -t rsa -b 2048 -f keys/rsa -N ""

script:
  - py.test -vxs --cov=iam tests
  - flake8 iam tests
  - isort --check-only --recursive iam tests
  - ./scripts/verify_license_headers.sh iam
  - pipenv check

after_success:
  - codecov
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

deploy:
  provider: script
  script: ./scripts/push_to_hub_travis.sh
  on:
    all_branches: true
