sudo: required
language: minimal

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/iam
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}
  matrix:
    - TARGET=test-travis
    - TARGET=pipenv-check
    - TARGET=flake8
    - TARGET=isort
    - TARGET=license

matrix:
  fast_finish: true

install:
  - ./scripts/install_gcloud.sh

before_script:
  - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin

script:
  - docker pull ${IMAGE}
  - make setup ${TARGET}

stages:
  - build
  - test
  - push-tags
  - name: deploy-staging
    if: branch = devel
  - name: deploy-production
    if: branch = master

jobs:
  include:
    - stage: build
      install:
        - ./scripts/install_gcloud.sh
        - echo ${DOCKER_PASSWORD} | docker login -u=decaftravis --password-stdin
      before_script:
        - docker build -t ${IMAGE} .
        - docker push ${IMAGE}
      script: skip
    - stage: push-tags
      install:
        - ./scripts/install_gcloud.sh
      before_script:
        - docker pull ${IMAGE}
        - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
        - docker tag ${IMAGE} ${IMAGE_REPO}:${TRAVIS_BRANCH}
        - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
        - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}
      script: skip
    - stage: deploy-staging
      install:
        - ./scripts/install_kubectl.sh
      script: skip
      deploy:
        provider: script
        script: ./scripts/travis_deploy.sh iam-staging
    - stage: deploy-production
      install:
        - ./scripts/install_kubectl.sh
      script: skip
      deploy:
        provider: script
        script: ./scripts/travis_deploy.sh iam-production

notifications:
  email: false
  slack:
    rooms:
      - ${SLACK_ACCOUNT}:${SLACK_TOKEN}#${SLACK_CHANNEL}
    on_success: never
    on_failure: always
    on_pull_requests: false
