version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/dd-decaf-cfbf6/iam:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - iam
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
      - type: tmpfs
        target: "/prometheus-client"
    depends_on:
      - postgres
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SCRIPT_NAME=${SCRIPT_NAME}
      - FLASK_APP=src/iam/wsgi.py
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - SENTRY_DSN=${SENTRY_DSN}
      - SERVICE_URL=${SERVICE_URL}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - FEAT_TOGGLE_LOCAL_AUTH=${FEAT_TOGGLE_LOCAL_AUTH:-1}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-iam}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - FEAT_TOGGLE_FIREBASE=${FEAT_TOGGLE_FIREBASE}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - prometheus_multiproc_dir=/prometheus-client
    command: gunicorn -c gunicorn.py iam.wsgi:app

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default

networks:
  DD-DeCaF:
    external: true
