version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_TAG=${BASE_TAG}
        - BUILD_COMMIT=${BUILD_COMMIT:-unknown}
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-unknown}
    image: gcr.io/dd-decaf-cfbf6/iam:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - iam
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
      - type: tmpfs
        target: "/prometheus-client"
    depends_on:
      - postgres
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/iam/wsgi.py
      - SCRIPT_NAME=${SCRIPT_NAME}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200}
      - SENTRY_DSN=${SENTRY_DSN}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - FEAT_TOGGLE_LOCAL_AUTH=${FEAT_TOGGLE_LOCAL_AUTH:-1}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-iam}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - FEAT_TOGGLE_FIREBASE=${FEAT_TOGGLE_FIREBASE}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-dd-decaf-cfbf6}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - prometheus_multiproc_dir=/prometheus-client
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default

networks:
  DD-DeCaF:
    external: true
