version: "3.1" # note: pycharm does not support newer versions than this
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
    environment:
      - FLASK_APP=iam/main.py
      - ENVIRONMENT=development
      - SERVICE_URL=
      - SENTRY_DSN=
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=
      - FEAT_TOGGLE_LOCAL_AUTH=1
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:@postgres:5432/iam
      - FEAT_TOGGLE_FIREBASE=
    depends_on:
      - postgres
    networks:
      - iloop
    command: gunicorn -c gunicorn.py iam.main:app

  postgres:
    image: postgres:10-alpine
    volumes:
      - /var/lib/postgresql/data
    networks:
      - iloop

networks:
  iloop:
    external: true
