version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dddecaf/iam:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - iam
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/iam/wsgi.py
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - SENTRY_DSN=${SENTRY_DSN}
      - SERVICE_URL=${SERVICE_URL}
      - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
      - FEAT_TOGGLE_LOCAL_AUTH=${FEAT_TOGGLE_LOCAL_AUTH:-1}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-postgres://postgres:@postgres:5432/iam}
      - FEAT_TOGGLE_FIREBASE=${FEAT_TOGGLE_FIREBASE}
    command: gunicorn -c gunicorn.py iam.wsgi:app

  postgres:
    image: postgres:10-alpine
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default

networks:
  DD-DeCaF:
    external: true
