apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iam-legacy
spec:
  tls:
  - hosts:
    - api.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: api.dd-decaf.eu
    http:
      paths:
      - path: /iam
        backend:
          serviceName: iam-legacy
          servicePort: 80
