kind: Service
apiVersion: v1
metadata:
  name: iam-legacy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: iam
    env: legacy
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 8000
