"""empty message

Revision ID: 10ed4b37ed10
Revises: 4f90a957e5df
Create Date: 2018-02-15 12:34:11.216761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ed4b37ed10'
down_revision = '4f90a957e5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_expiry')
    # ### end Alembic commands ###
