"""empty message

Revision ID: 24c577d516c9
Revises: c274a3515ca4
Create Date: 2018-02-15 16:28:49.755890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c577d516c9'
down_revision = 'c274a3515ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('project', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('firebase_token', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('firebase_uid', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firebase_uid')
    op.drop_column('user', 'firebase_token')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.alter_column('project', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
