"""empty message

Revision ID: 44593635f9d6
Revises: afe67bd50b31
Create Date: 2018-02-14 17:50:14.332816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44593635f9d6'
down_revision = 'afe67bd50b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
