"""empty message

Revision ID: 4f90a957e5df
Revises: 20e054300e58
Create Date: 2018-02-15 12:14:57.281720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f90a957e5df'
down_revision = '20e054300e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
