"""Add consent model

Revision ID: 87e272ec75ad
Revises: e895b1eb485b
Create Date: 2020-01-24 11:57:45.952411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e272ec75ad'
down_revision = 'e895b1eb485b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('gdpr', 'cookie', name='consenttype'), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', name='consentstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consent')
    # ### end Alembic commands ###
