"""empty message

Revision ID: e0a0bd4725f0
Revises: b3cd17ab84b1
Create Date: 2018-12-11 16:47:10.147653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0a0bd4725f0'
down_revision = 'b3cd17ab84b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=True),
    sa.Column('refresh_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'refresh_token_expiry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
