"""empty message

Revision ID: e895b1eb485b
Revises: e0a0bd4725f0
Create Date: 2019-01-03 13:41:06.988218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e895b1eb485b'
down_revision = 'e0a0bd4725f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('expiry', sa.DateTime(), nullable=True))
    op.add_column('refresh_token', sa.Column('token', sa.String(length=64), nullable=True))
    op.drop_column('refresh_token', 'refresh_token')
    op.drop_column('refresh_token', 'refresh_token_expiry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('refresh_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('refresh_token', sa.Column('refresh_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('refresh_token', 'token')
    op.drop_column('refresh_token', 'expiry')
    # ### end Alembic commands ###
