"""empty message

Revision ID: f5f11b928403
Revises: 24c577d516c9
Create Date: 2018-02-15 16:59:42.699808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f11b928403'
down_revision = '24c577d516c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'firebase_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firebase_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
